### ISSUE TITLE
Python error in collector

### ISSUE THREAD

**Issue by chrisjeter** [recklessop/Zerto_Exporter#23]
Running two separate collector instances both returning this same error.  Container image is deployed off of zerto-exporter:stable. Zerto version is 10.0u1 patch 1 build 10011120159

Exception in thread Thread-828 (GetStatsFunc):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1052, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 989, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/src/app/python-node-exporter.py", line 207, in GetStatsFunc
    CurrentEncryptedLBs               = abs(vm['EncryptionStatistics']['EncryptedDataInLBs'] - oldvmdata[0]['EncryptionStatistics']['EncryptedDataInLBs'])
                                            ~~^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'EncryptionStatistics'

**Comment by recklessop** [comment]
Are you on Zerto 10.0 or 9.7 ?

**Comment by recklessop** [comment]
This should be fixed now in the latest code.
